### ISSUE TITLE
Ignore Nicknames

### ISSUE THREAD

**Issue by kylef** [cocodelabs/palaver-l10n#18]
Palaver now has support for ignoring nicknames (in 84bf595e1b73bf4af070bfac297ef89dfa03f46c) using the following keys:
- `NICK_IGNORE` (Ignore)
- `NICK_UNIGNORE` (Stop Ignoring)
- `NETWORK_IGNORED_NICKS` (Ignored Nicknames)
- `QUERY_STATUS_NICK_IGNORED` (Nickname Ignored)
- `QUERY_STATUS_NICK_IGNORED_ACTION` (Tap here to stop ignoring this user.)

Screenshots of these features:

![screen shot 2015-10-14 at 15 33 58](https://cloud.githubusercontent.com/assets/44164/10499938/06e056ee-7289-11e5-8fb0-060b6b0a52f5.png)
![screen shot 2015-10-14 at 15 34 06](https://cloud.githubusercontent.com/assets/44164/10499940/07955a6c-7289-11e5-942b-961c1106677a.png)

**Comment by iamDecode** [comment]
Added in #29
